# Fake Controllers Configuration

controller_list: # Arm Controllers
  - name: fake_arm_controller
    joints:
      - joint1
      - joint2
      - joint4
      - joint5
      - joint6
      - joint7
  - name: fake_hand_controller # Hand Controllers
    joints:
      - index_prox
      - ring_prox
      - thumb_base
      - thumb_prox