# Joint Limits Configuration
# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  index_prox:
    has_velocity_limits: true
    max_velocity: 4.18879020479
    has_acceleration_limits: false
    max_acceleration: 0
  joint1:
    has_velocity_limits: true
    max_velocity: 2.09439510239
    has_acceleration_limits: false
    max_acceleration: 0
  joint2:
    has_velocity_limits: true
    max_velocity: 2.09439510239
    has_acceleration_limits: false
    max_acceleration: 0
  joint4:
    has_velocity_limits: true
    max_velocity: 2.09439510239
    has_acceleration_limits: false
    max_acceleration: 0
  joint5:
    has_velocity_limits: true
    max_velocity: 2.09439510239
    has_acceleration_limits: false
    max_acceleration: 0
  joint6:
    has_velocity_limits: true
    max_velocity: 2.09439510239
    has_acceleration_limits: false
    max_acceleration: 0
  joint7:
    has_velocity_limits: true
    max_velocity: 2.09439510239
    has_acceleration_limits: false
    max_acceleration: 0
  ring_prox:
    has_velocity_limits: true
    max_velocity: 4.18879020479
    has_acceleration_limits: false
    max_acceleration: 0
  thumb_base:
    has_velocity_limits: true
    max_velocity: 4.18879020479
    has_acceleration_limits: false
    max_acceleration: 0
  thumb_prox:
    has_velocity_limits: true
    max_velocity: 4.18879020479
    has_acceleration_limits: false
    max_acceleration: 0